defaults:
  - logger: logger
  - arch: anakin
  - system: q_learning/ff_dqn_ortho
  - network: mlp_dqn_groupsort  # Default to groupsort for isometric study
  - env: gymnax/cartpole
  - _self_

hydra:
  searchpath:
    - file://stoix/configs
